runtime: python27
api_version: 1
threadsafe: true
service: post

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always

libraries:
- name: ssl
  version: latest

skip_files:
- node_modules/
- .git/
- .gitignore
- README.md
- LICENSE
- package.json
- package-lock.json
- .idea/
